const $=selector=>document.querySelector(selector);let state={products:[],editing:null};
async function api(path,options={}){const response=await fetch(path,{...options,headers:{Accept:'application/json',...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(response.status===401){location.href='/owner/login.html';throw new Error('Sign-in required.')}if(!response.ok)throw new Error(body.error||`Request failed (${response.status}).`);return body}
const money=cents=>(Number(cents||0)/100).toFixed(2);
function addVariation(value={name:'',priceCents:1500,quantity:0}){const row=$('#variationTemplate').content.firstElementChild.cloneNode(true);row.querySelector('[data-field=name]').value=value.name;row.querySelector('[data-field=price]').value=money(value.priceCents);row.querySelector('[data-field=quantity]').value=value.quantity;row.dataset.squareVariationId=value.squareVariationId||'';row.querySelector('[data-remove]').addEventListener('click',()=>{if($('#variations').children.length>1)row.remove()});$('#variations').append(row)}
function readVariations(){return [...document.querySelectorAll('.variation-row')].map(row=>({name:row.querySelector('[data-field=name]').value.trim(),priceCents:Math.round(Number(row.querySelector('[data-field=price]').value)*100),quantity:Number(row.querySelector('[data-field=quantity]').value),squareVariationId:row.dataset.squareVariationId||null}))}
function clearForm(){state.editing=null;$('#productForm').reset();$('#productId').value='';$('#variations').innerHTML='';addVariation();$('#photoForm').hidden=true;$('#stageArea').hidden=true;$('#photoPreview').hidden=true;$('#productStatus').textContent='';$('#photoStatus').textContent=''}
function editProduct(id){const p=state.products.find(item=>item.id===id);if(!p)return;state.editing=p;$('#productId').value=p.id;$('#productName').value=p.name;$('#productCategory').value=p.category;$('#productFulfillment').value=p.fulfillment;$('#productDescription').value=p.description||'';$('#variations').innerHTML='';p.variations.forEach(addVariation);$('#photoForm').hidden=false;$('#stageArea').hidden=false;if(p.image_key){$('#photoPreview').src=`/api/owner/images/${encodeURIComponent(p.image_key)}`;$('#photoPreview').hidden=false}else $('#photoPreview').hidden=true;$('#productForm').scrollIntoView({behavior:'smooth',block:'start'})}
function render(){const box=$('#productList');if(!state.products.length){box.innerHTML='<p class="notice">No owner-created drafts yet. The existing public lineup remains unchanged until its controlled Square reconciliation.</p>';return}box.innerHTML='';state.products.forEach(p=>{const item=document.createElement('article');item.className='saved-product';const visual=p.image_key?`<img src="/api/owner/images/${encodeURIComponent(p.image_key)}" alt="">`:'<div class="image-placeholder"></div>';item.innerHTML=`${visual}<div><span class="tag">${p.status.replaceAll('_',' ')}</span><h3>${p.name}</h3><p>${p.category} · ${p.variations.length} variation${p.variations.length===1?'':'s'} · ${p.fulfillment.replaceAll('_',' ')}</p></div><button class="secondary" type="button">Review</button>`;item.querySelector('button').addEventListener('click',()=>editProduct(p.id));box.append(item)})}
async function load(){try{const data=await api('/api/owner/bootstrap');state.products=data.products;$('#fundraiserEnabled').checked=data.settings.fundraiserEnabled;$('#fundraiserName').value=data.settings.fundraiserName||'';$('#fundraiserMessage').value=data.settings.fundraiserMessage||'';updateFundraiserState();const status=$('#squareStatus');if(data.square.connected){status.className='status-card ok';status.textContent=`Square connected · ${data.square.location} · ${data.square.mode}`}else{status.className='status-card warn';status.textContent=data.square.configured?`Square connection needs attention · ${data.square.error||'verification failed'}`:'Draft mode · Square authorization is scheduled but not connected'}render()}catch(error){$('#squareStatus').className='status-card warn';$('#squareStatus').textContent=error.message}}
function updateFundraiserState(){const on=$('#fundraiserEnabled').checked;$('#fundraiserState').textContent=on?'On':'Off';$('#fundraiserState').classList.toggle('on',on)}
$('#fundraiserEnabled').addEventListener('change',updateFundraiserState);$('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const status=$('#settingsStatus');status.textContent='Saving…';try{await api('/api/owner/settings',{method:'PUT',body:JSON.stringify({fundraiserEnabled:$('#fundraiserEnabled').checked,fundraiserName:$('#fundraiserName').value,fundraiserMessage:$('#fundraiserMessage').value})});status.textContent='Saved. The storefront will use this setting.'}catch(error){status.textContent=error.message}});
$('#addVariation').addEventListener('click',()=>addVariation());$('#newProduct').addEventListener('click',clearForm);$('#productForm').addEventListener('submit',async event=>{event.preventDefault();const status=$('#productStatus');status.textContent='Saving draft…';try{const result=await api('/api/owner/products',{method:'POST',body:JSON.stringify({id:$('#productId').value||undefined,name:$('#productName').value,category:$('#productCategory').value,fulfillment:$('#productFulfillment').value,description:$('#productDescription').value,variations:readVariations()})});$('#productId').value=result.id;status.textContent='Draft saved. You can now upload its approved photo.';$('#photoForm').hidden=false;$('#stageArea').hidden=false;await load();editProduct(result.id)}catch(error){status.textContent=error.message}});
$('#photoForm').addEventListener('submit',async event=>{event.preventDefault();const id=$('#productId').value,file=$('#productPhoto').files[0],status=$('#photoStatus');if(!id||!file)return;status.textContent='Uploading…';const form=new FormData();form.set('photo',file);try{const result=await api(`/api/owner/products/${encodeURIComponent(id)}/photo`,{method:'POST',body:form});$('#photoPreview').src=result.imageUrl;$('#photoPreview').hidden=false;status.textContent='Photo uploaded to the protected product record.';await load();editProduct(id)}catch(error){status.textContent=error.message}});
$('#stageProduct').addEventListener('click',async()=>{const id=$('#productId').value,status=$('#productStatus');if(!id)return;status.textContent='Checking draft…';try{const result=await api(`/api/owner/products/${encodeURIComponent(id)}/stage`,{method:'POST',body:'{}'});status.textContent=result.message;await load();editProduct(id)}catch(error){status.textContent=error.message}});clearForm();load();
