const products = {
  furmama: {name:'Cherry Red shirt: Fur Mama',color:'Cherry Red · white letters · Gildan Unisex Softstyle',image:'assets/fur-mama-red-studio-DRAFT.png',sizes:{Small:{qty:1,price:15},Medium:{qty:2,price:15},Large:{qty:1,price:15},XL:{qty:1,price:15},'2XL':{qty:1,price:18},'3XL':{qty:1,price:18}}},
  dogdad: {name:'Black shirt: Best Dog Dad Ever',color:'Black · white letters · Gildan Unisex Softstyle',image:'assets/best-dog-dad-black-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:0,price:15},Large:{qty:0,price:15},XL:{qty:1,price:15},'2XL':{qty:1,price:18},'3XL':{qty:1,price:18}}},
  adopt: {name:'Sport Gray shirt: Adopt / Foster / Rescue',color:'Sport Gray · black letters · Gildan Unisex Softstyle',image:'assets/adopt-foster-rescue-sport-gray-studio-APPROVED.png',sizes:{Small:{qty:1,price:15},Medium:{qty:1,price:15},Large:{qty:0,price:15},XL:{qty:2,price:15},'2XL':{qty:1,price:18},'3XL':{qty:0,price:18}}},
  dogdadblue: {name:'Blue shirt: Best Dog Dad Ever',color:'Blue · white letters · Gildan Unisex Softstyle',image:'assets/best-dog-dad-blue-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:0,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:1,price:18},'3XL':{qty:0,price:18}}},
  dogdadgray: {name:'Sport Gray shirt: Best Dog Dad Ever',color:'Sport Gray · black letters · Gildan Unisex Softstyle',image:'assets/best-dog-dad-gray-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:0,price:15},Large:{qty:0,price:15},XL:{qty:1,price:15},'2XL':{qty:2,price:18},'3XL':{qty:0,price:18}}},
  dudesblock: {name:'Sage shirt: Dogs Before Dudes',color:'Sage · black block letters · Gildan Unisex Softstyle',image:'assets/dogs-before-dudes-sage-block-color-corrected-2026-08-20.png',sizes:{Small:{qty:0,price:15},Medium:{qty:1,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:1,price:18},'3XL':{qty:0,price:18}}},
  dudesscript: {name:'Sage shirt: Dogs Before Dudes',color:'Sage · black letters with two paws · Gildan Unisex Softstyle',image:'assets/dogs-before-dudes-sage-script-color-corrected-2026-08-20.png',sizes:{Small:{qty:1,price:15},Medium:{qty:1,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  dudesheart: {name:'Heather Purple shirt: Dogs Before Dudes',color:'Heather Purple · white script letters · Gildan Unisex Softstyle',image:'assets/dogs-before-dudes-purple-heart-studio-DRAFT.png',sizes:{Small:{qty:1,price:15},Medium:{qty:1,price:15},Large:{qty:1,price:15},XL:{qty:1,price:15},'2XL':{qty:1,price:18},'3XL':{qty:1,price:18}}},
  furmamablue: {name:'Blue shirt: Fur Mama',color:'Blue · white letters · Gildan Unisex Softstyle',image:'assets/fur-mama-blue-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:1,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:1,price:18}}},
  infinityblue: {name:'Blue shirt: All White Infinity',color:'Blue · all-white infinity · Gildan Unisex Softstyle',image:'assets/paw-heart-infinity-blue-white-studio-DRAFT.png',sizes:{Small:{qty:1,price:15},Medium:{qty:0,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  infinitypinkblack: {name:'Azalea shirt: Black Infinity with Red Heart',color:'Azalea (pink) · Gildan Unisex Softstyle',image:'assets/paw-heart-infinity-pink-black-red-studio-DRAFT.png',sizes:{Small:{qty:1,price:15},Medium:{qty:1,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:1,price:18},'3XL':{qty:0,price:18}}},
  infinitypinkblue: {name:'Azalea shirt: White Infinity with Blue Heart',color:'Azalea (pink) · Gildan Unisex Softstyle',image:'assets/paw-heart-infinity-pink-white-blue-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:1,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  infinitypinkred: {name:'Azalea shirt: White Infinity with Red Heart',color:'Azalea (pink) · Gildan Unisex Softstyle',image:'assets/paw-heart-infinity-pink-white-red-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:0,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:1,price:18}}},
  infinityyellow: {name:'Daisy shirt: Black Infinity with Blue Heart',color:'Daisy (yellow) · Gildan Unisex Softstyle',image:'assets/paw-heart-infinity-yellow-black-blue-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:1,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  tellpurple: {name:'Heather Purple shirt: Tell Your Dog I Said Hi',color:'Heather Purple · white print with blue paw · Gildan Unisex Softstyle',image:'assets/tell-your-dog-purple-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:1,price:15},Large:{qty:0,price:15},XL:{qty:0,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  tellwhite: {name:'White shirt: Tell Your Dog I Said Hi',color:'White · black print with red paw · Gildan Unisex Softstyle',image:'assets/tell-your-dog-white-studio-DRAFT.png',sizes:{Small:{qty:0,price:15},Medium:{qty:0,price:15},Large:{qty:0,price:15},XL:{qty:1,price:15},'2XL':{qty:2,price:18},'3XL':{qty:0,price:18}}},
  tellyellow: {name:'Daisy shirt: Tell Your Dog I Said Hi',color:'Daisy (yellow) · black print with blue paw · Gildan Unisex Softstyle',image:'assets/tell-your-dog-yellow-studio-DRAFT.png',sizes:{Small:{qty:1,price:15},Medium:{qty:0,price:15},Large:{qty:1,price:15},XL:{qty:1,price:15},'2XL':{qty:1,price:18},'3XL':{qty:1,price:18}}},
  sage: {name:'Cats Are My Favorite People',color:'Sage green',image:'assets/cats-favorite-people-sage.jpg',sizes:{Small:{qty:1,price:15},Medium:{qty:2,price:15},Large:{qty:2,price:15},XL:{qty:1,price:15},'2XL':{qty:0,price:18},'3XL':{qty:0,price:18}}},
  purple: {name:'Cats with Heart & Paws',color:'Heather purple',image:'assets/cats-heart-paws-purple.jpg',sizes:{Small:{qty:1,price:15},Medium:{qty:2,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:2,price:18},'3XL':{qty:0,price:18}}},
  catrescued: {name:'We Rescued Each Other',color:'White, Black, and Blue · Gildan Unisex Softstyle',image:'assets/cat-we-rescued-each-other-studio-2026-08-20.png',sizes:{'White · Small':{qty:1,price:15},'White · 3XL':{qty:1,price:18},'Black · Small':{qty:1,price:15},'Black · Large':{qty:1,price:15},'Blue · Small':{qty:1,price:15},'Blue · Medium':{qty:2,price:15},'Blue · Large':{qty:2,price:15},'Blue · XL':{qty:1,price:15},'Blue · 2XL':{qty:1,price:18},'Blue · 3XL':{qty:1,price:18}}},
  rescuecats: {name:'I Just Want to Rescue All the Cats',color:'Sport Gray and White · Gildan Unisex Softstyle',image:'assets/cat-rescue-all-cats-studio-2026-08-20.png',sizes:{'Sport Gray · Small':{qty:2,price:15},'Sport Gray · Medium':{qty:1,price:15},'Sport Gray · Large':{qty:2,price:15},'Sport Gray · XL':{qty:1,price:15},'Sport Gray · 3XL':{qty:1,price:18},'White · XL':{qty:1,price:15}}},
  catadopt: {name:'Rescue · Foster · Adopt',color:'Black and White · Gildan Unisex Softstyle',image:'assets/cat-rescue-foster-adopt-studio-2026-08-20.png',sizes:{'Black · Small':{qty:1,price:15},'Black · Medium':{qty:2,price:15},'Black · Large':{qty:2,price:15},'Black · XL':{qty:2,price:15},'Black · 3XL':{qty:1,price:18},'White · Medium':{qty:1,price:15},'White · Large':{qty:1,price:15}}},
  savingcats: {name:'Saving Cats Is Kinda My Thing',color:'Daisy Yellow · black/blue or white print · Gildan Unisex Softstyle',image:'assets/cat-saving-cats-studio-2026-08-20.png',sizes:{'Daisy · Small · black/blue print':{qty:1,price:15},'Daisy · Medium · black/blue print':{qty:1,price:15},'Daisy · Medium · white print':{qty:1,price:15},'Daisy · Large · black/blue print':{qty:1,price:15},'Daisy · Large · white print':{qty:1,price:15},'Daisy · XL':{qty:2,price:15},'Daisy · 3XL':{qty:1,price:18}}},
  loverescued: {name:'Love Rescued Me',color:'Azalea Pink · black/blue or white print · Gildan Unisex Softstyle',image:'assets/cat-love-rescued-me-studio-2026-08-20.png',sizes:{'Azalea · Small · black/blue print':{qty:1,price:15},'Azalea · Medium · black/blue print':{qty:1,price:15},'Azalea · Medium · white print':{qty:1,price:15},'Azalea · Large · black/blue print':{qty:1,price:15},'Azalea · Large · white print':{qty:1,price:15},'Azalea · XL':{qty:2,price:15},'Azalea · 2XL':{qty:1,price:18},'Azalea · 3XL':{qty:1,price:18}}},
  rescuecatmom: {name:'Proud Rescue Cat Mom',color:'Cherry Red · black/blue or white print · Gildan Unisex Softstyle',image:'assets/cat-proud-rescue-mom-studio-2026-08-20.png',sizes:{'Cherry Red · Small':{qty:1,price:15},'Cherry Red · Medium · black print':{qty:1,price:15},'Cherry Red · Medium · white print':{qty:1,price:15},'Cherry Red · Large':{qty:2,price:15},'Cherry Red · 2XL':{qty:1,price:18},'Cherry Red · 3XL':{qty:1,price:18}}},
  penholder: {name:'Paw Print Bookmark Pen Holder',color:'Multiple pet-print patterns',image:'assets/bookmark-holder-dog-hearts-paws.jpg',sizes:{'One size':{qty:null,price:10}}},
  fabricbag: {name:'Pet-Print Fabric Bag',color:'Multiple patterns',image:'assets/fabric-bag-black-blue.jpg',sizes:{'One size':{qty:null,price:20}}},
  handtowel: {name:'Pet-Themed Hand Towel',color:'Multiple designs',image:'assets/hand-towel-dog-cat-heart.png',sizes:{'One size':{qty:null,price:10}}}
};
const accessoryCatalog=[
  ['holdercatblack','Black Cats Pencil Holder','holders','Pencil holder','assets/holder-cat-black.jpg',10],['holdercatclassroom','Classroom Cats Pencil Holder','holders','Pencil holder','assets/holder-cat-classroom.jpg',10],['holdercatrainbow','Rainbow Cats Pencil Holder','holders','Pencil holder','assets/holder-cat-rainbow.jpg',10],['holdercatwhite','White Cats Pencil Holder','holders','Pencil holder','assets/holder-cat-white.jpg',10],['holderdoghearts','Dog Hearts, Paws & Bones Pencil Holder','holders','Pencil holder','assets/holder-dog-hearts-paws-bones.jpg',10],['holderdogbones','Dog Paws & Bones Pencil Holder','holders','Pencil holder','assets/holder-dog-paws-bones.jpg',10],['holderdogred','Red Dog Paws Pencil Holder','holders','Pencil holder','assets/holder-dog-red-paws.jpg',10],['holderdogwoof','Woof & Grrr Dogs Pencil Holder','holders','Pencil holder','assets/holder-dog-woof-grrr.jpg',10],
  ['towel250','America 250th Hand Towel','towels','Hand towel','assets/towel-america-250th.png',10],['towelamericapaw','America with Paw Hand Towel','towels','Hand towel','assets/towel-america-paw.png',10],['towelbrownhome','Brown Home Sweet Home Hand Towel','towels','Hand towel','assets/towel-brown-home-sweet-home.png',10],['toweldogcat','Dog & Cat with Heart Hand Towel','towels','Hand towel','assets/towel-dog-cat-heart.png',10],['towelhotpink','Hot Pink Heart & Paw Hand Towel','towels','Hand towel','assets/towel-hot-pink-heart-paw.png',10],['towelfreedom','Paws Off My Freedom Hand Towel','towels','Hand towel','assets/towel-paws-off-my-freedom.png',10],['towelpurplehome','Purple Home Sweet Home Hand Towel','towels','Hand towel','assets/towel-purple-home-sweet-home.png',10],['towelredheart','Red Heart & Paw Hand Towel','towels','Hand towel','assets/towel-red-heart-paw.png',10],['towelrusthome','Rust Home Sweet Home Hand Towel','towels','Hand towel','assets/towel-rust-home-sweet-home.jpg',10],
  ['bagblackblue','Black & Blue Circle Fabric Bag','bags','Fabric bag','assets/bag-black-blue-circle.jpg',20],['bagbrowndogs','Brown Dogs Circle Fabric Bag','bags','Fabric bag','assets/bag-brown-dogs-circle.jpg',20],['baggreen','Green Pet Print Fabric Bag','bags','Fabric bag','assets/bag-green-fabric.jpg',20],['baglightblue','Light Blue Pet Print Fabric Bag','bags','Fabric bag','assets/bag-light-blue-fabric.jpg',20],['bagpatriot','Patriot Circle Fabric Bag','bags','Fabric bag','assets/bag-patriot-circle.jpg',20],['bagpink','Pink Pet Print Fabric Bag','bags','Fabric bag','assets/bag-pink-fabric.jpg',20],['bagrainbow','Rainbow Bones Circle Fabric Bag','bags','Fabric bag','assets/bag-rainbow-bones-circle.jpg',20],['bagredblack','Red & Black Circle Fabric Bag','bags','Fabric bag','assets/bag-red-black-circle.jpg',20],['bagredplaid','Red Plaid Fabric Bag','bags','Fabric bag','assets/bag-red-plaid-fabric.jpg',20],['bagredpaws','Red Paws & Swirls Circle Fabric Bag','bags','Fabric bag','assets/bag-red-paws-swirl-circle.jpg',20],
  ['potholderdogmom','All American Dog Mom Pot Holder','potholders','Potholder','assets/Pot%20Holders/All%20American%20Dog%20Mom%20Pot%20Holder.png',null],['potholder250','America 250 Years Pot Holder','potholders','Potholder','assets/Pot%20Holders/America%20250%20Years%20Pot%20Holder.png',null],['potholderblue','Blue Quilted Pot Holder','potholders','Potholder','assets/Pot%20Holders/Blue%20Quilted%20Pot%20Holder.png',null],['potholderembroidered','Embroidered Pot Holder','potholders','Potholder','assets/Pot%20Holders/Embroidered%20Pot%20Holder.png',null],['potholdergreen','Green Quilted Pot Holder','potholders','Potholder','assets/Pot%20Holders/Green%20Quilted%20Pot%20Holder.png',null],['potholderpatriotic','Patriotic Quilted Pot Holder','potholders','Potholder','assets/Pot%20Holders/Patriotic%20Quilted%20Pot%20Holder.png',null],['potholderred','Red Quilted Pot Holder','potholders','Potholder','assets/Pot%20Holders/Red%20Quilted%20Pot%20Holder.jpg',null]
];
const productGrid=document.querySelector('.product-grid'),comingCard=productGrid.querySelector('.coming-card');
['penholder','fabricbag','handtowel'].forEach(id=>productGrid.querySelector(`[data-product="${id}"]`)?.closest('.product-card')?.remove());
accessoryCatalog.forEach(([id,name,category,label,image,price])=>{products[id]={name,color:`Handmade ${label.toLowerCase()}`,image,sizes:{'One size':{qty:null,price}}};const card=document.createElement('article');card.className='product-card';card.dataset.category=category;const priceText=price===null?'Price to confirm':`$${price} <span>plus tax</span>`;card.innerHTML=`<button class="product-image" type="button" data-product="${id}"><span class="badge soft">${label}</span><img src="${image}" alt="${name}"></button><div class="product-info"><div><p class="product-kicker">Handmade accessories</p><h3>${name}</h3></div><p class="price">${priceText}</p></div><p class="stock-note pending-stock"><span></span> Price and inventory to confirm in Square</p><button class="button secondary product-open" data-product="${id}" type="button">View details</button>`;productGrid.insertBefore(card,comingCard)});
const dialog=document.querySelector('#productDialog'),dialogImage=document.querySelector('#dialogImage'),dialogName=document.querySelector('#dialogName'),dialogColor=document.querySelector('#dialogColor'),dialogPrice=document.querySelector('#dialogPrice'),sizeGrid=document.querySelector('#sizeGrid'),sizeMessage=document.querySelector('#sizeMessage'),addButton=document.querySelector('#addToCart');
const drawer=document.querySelector('#cartDrawer'),scrim=document.querySelector('#scrim'),cartItems=document.querySelector('#cartItems'),cartTotal=document.querySelector('#cartTotal'),cartCount=document.querySelector('#cartCount'),checkoutButton=document.querySelector('#checkoutButton'),toast=document.querySelector('#toast'),fundraiserNameWrap=document.querySelector('#fundraiserNameWrap'),fundraiserName=document.querySelector('#fundraiserName'),fundraiserError=document.querySelector('#fundraiserError');
async function loadFundraiserSetting(){const fieldset=document.querySelector('.fundraiser-fieldset'),yes=document.querySelector('[name="supports_fundraiser"][value="yes"]'),no=document.querySelector('[name="supports_fundraiser"][value="no"]');if(!fieldset||!yes||!no)return;try{const response=await fetch('/api/storefront/settings',{headers:{Accept:'application/json'}});if(!response.ok)return;const setting=(await response.json()).fundraiser||{},options=fieldset.querySelector('.fundraiser-options'),legend=fieldset.querySelector('legend');fieldset.dataset.ownerControlled='true';if(!setting.enabled){fieldset.hidden=true;fieldset.style.display='none';no.checked=true;fundraiserNameWrap.hidden=true;fundraiserName.required=false;fundraiserName.value='';return}fieldset.hidden=false;fieldset.style.removeProperty('display');yes.checked=true;no.checked=false;yes.disabled=true;no.disabled=true;if(options){options.hidden=true;options.style.display='none'}fundraiserNameWrap.hidden=true;fundraiserNameWrap.style.display='none';fundraiserName.required=false;fundraiserName.value=setting.name||'';if(legend)legend.textContent=`Active fundraiser: ${setting.name}`;if(setting.message){const note=document.createElement('p');note.className='fundraiser-message';note.textContent=setting.message;legend.insertAdjacentElement('afterend',note)}}catch{/* GitHub Pages preview keeps its existing review controls until the hosted API is deployed. */}}
loadFundraiserSetting();
let activeProduct=null,activeSize=null,cart=[];
const reviewedVideoProducts=new Set(['furmama','dogdad','adopt','dogdadblue','dogdadgray','dudesblock','dudesscript','dudesheart','furmamablue','infinityblue','infinitypinkblack','infinitypinkblue','infinitypinkred','infinityyellow','tellpurple','tellwhite','tellyellow','catrescued','rescuecats','catadopt','savingcats','loverescued','rescuecatmom']);
function syncReviewedCatalogCards(){document.querySelectorAll('.product-card').forEach(card=>{const trigger=card.querySelector('[data-product]');if(!trigger||!reviewedVideoProducts.has(trigger.dataset.product))return;const p=products[trigger.dataset.product],total=Object.values(p.sizes).reduce((sum,item)=>sum+(Number(item.qty)||0),0);const title=card.querySelector('h3'),price=card.querySelector('.price'),stock=card.querySelector('.stock-note'),image=trigger.querySelector('img'),badge=trigger.querySelector('.badge'),button=card.querySelector('.product-open');if(title)title.textContent=p.name;if(price)price.innerHTML='$15 <span>2XL–3XL $18</span>';if(stock){stock.classList.remove('pending-stock');stock.innerHTML=`<span></span> ${total} shirt${total===1?'':'s'} in stock`}if(image){image.src=p.image;image.alt=p.name}if(badge){badge.textContent='Angelica approved';badge.classList.remove('soft')}if(button)button.textContent='Choose a size'})}
syncReviewedCatalogCards();
function openProduct(id){activeProduct=id;activeSize=null;const p=products[id];dialogImage.src=p.image;dialogImage.alt=p.name;dialogName.textContent=p.name;dialogColor.textContent=p.color;const first=Object.values(p.sizes)[0];dialogPrice.textContent=first.price===null?'Price to confirm':`$${first.price}`;sizeGrid.innerHTML='';Object.entries(p.sizes).forEach(([size,data])=>{const b=document.createElement('button');b.type='button';b.className='size-option';b.disabled=data.qty===0||data.qty===null;const detail=data.qty===null?'Inventory to confirm in Square':data.qty?`${data.qty} left · $${data.price}`:'Sold out';b.innerHTML=`<strong>${size}</strong><small>${detail}</small>`;b.addEventListener('click',()=>selectSize(size,b));sizeGrid.appendChild(b)});sizeMessage.textContent=first.qty===null?'Price confirmed; inventory must be matched in Square before purchase.':'Select an available size to continue.';addButton.textContent='Add to bag';addButton.disabled=true;dialog.showModal()}
function selectSize(size,button){activeSize=size;document.querySelectorAll('.size-option').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');const data=products[activeProduct].sizes[size];if(data.price===null){dialogPrice.textContent='Price to confirm';sizeMessage.textContent='Square item setup is needed before checkout can be enabled.';addButton.textContent='Available after Square setup';addButton.disabled=true;return}dialogPrice.textContent=`$${data.price}`;sizeMessage.textContent=`${data.qty} available in ${size}.`;addButton.textContent='Add to bag';addButton.disabled=false}
function addToCart(){if(!activeProduct||!activeSize)return;const p=products[activeProduct],d=p.sizes[activeSize];cart.push({id:crypto.randomUUID(),product:activeProduct,size:activeSize,price:d.price});dialog.close();renderCart();showToast(`${p.name} · ${activeSize} added to your bag`);openCart()}
function renderCart(){cartCount.textContent=cart.length;checkoutButton.disabled=!cart.length;if(!cart.length){cartItems.innerHTML='<p class="empty-cart">Your bag is waiting for something happy.</p>'}else{cartItems.innerHTML=cart.map(item=>{const p=products[item.product];return `<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${p.color} · ${item.size}</p><button data-remove="${item.id}" type="button">Remove</button></div><strong>$${item.price}</strong></div>`}).join('')}cartTotal.textContent=`$${cart.reduce((sum,item)=>sum+item.price,0).toFixed(2)}`;document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart=cart.filter(i=>i.id!==b.dataset.remove);renderCart()}))}
function openCart(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.classList.add('show')}function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.classList.remove('show')}function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.product)));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});addButton.addEventListener('click',addToCart);document.querySelector('#openCart').addEventListener('click',openCart);document.querySelector('#closeCart').addEventListener('click',closeCart);scrim.addEventListener('click',closeCart);document.querySelectorAll('[name="supports_fundraiser"]').forEach(radio=>radio.addEventListener('change',()=>{if(document.querySelector('.fundraiser-fieldset')?.dataset.ownerControlled==='true')return;const supporting=radio.value==='yes';fundraiserNameWrap.hidden=!supporting;fundraiserName.required=supporting;if(!supporting)fundraiserName.value='';fundraiserError.textContent=''}));checkoutButton.addEventListener('click',()=>{const choice=document.querySelector('[name="supports_fundraiser"]:checked');if(!choice){fundraiserError.textContent='Please select Yes or No before continuing.';return}if(choice.value==='yes'&&!fundraiserName.value.trim()){fundraiserError.textContent='Please enter the rescue or fundraiser name.';fundraiserName.focus();return}fundraiserError.textContent='';const association=choice.value==='yes'?fundraiserName.value.trim():'No association';showToast(`Fundraiser: ${association} · Square checkout connection is next.`)});
const categoryTags={furmama:['dogs'],furmamablue:['dogs'],infinityblue:['dogs'],infinitypinkblack:['dogs'],infinitypinkblue:['dogs'],infinitypinkred:['dogs'],infinityyellow:['dogs'],sage:['cats'],purple:['cats'],catrescued:['cats'],rescuecats:['cats'],catadopt:['cats'],savingcats:['cats'],loverescued:['cats'],rescuecatmom:['cats'],adopt:['dogs'],dogdad:['dogs'],dogdadblue:['dogs'],dogdadgray:['dogs'],dudesblock:['dogs'],dudesscript:['dogs'],dudesheart:['dogs'],tellpurple:['dogs'],tellwhite:['dogs'],tellyellow:['dogs'],penholder:['gifts'],fabricbag:['gifts'],handtowel:['gifts']};
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.product-card').forEach(card=>{const productId=card.querySelector('[data-product]')?.dataset.product;const tags=categoryTags[productId]||card.dataset.category?.split(/\s+/)||[];card.hidden=button.dataset.filter!=='all'&&!tags.includes(button.dataset.filter)})}));
const storyForm=document.querySelector('#storyForm'),storyFormStatus=document.querySelector('#storyFormStatus');storyForm.addEventListener('submit',async event=>{event.preventDefault();const submitButton=storyForm.querySelector('[type="submit"]');submitButton.disabled=true;submitButton.textContent='Sending…';storyFormStatus.className='form-status';storyFormStatus.textContent='Sending your story…';try{const response=await fetch(storyForm.action,{method:'POST',body:new FormData(storyForm),headers:{Accept:'application/json'}});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.error||'Submission failed')}storyForm.reset();storyFormStatus.classList.add('success');storyFormStatus.textContent='Thank you! Your Happy Tail Story was sent for review.'}catch(error){storyFormStatus.classList.add('error');storyFormStatus.textContent=`We could not send your story: ${error.message}. Please try again.`}finally{submitButton.disabled=false;submitButton.textContent='Submit your story'}});
