const products = {
  furmama: {name:'Fur Mama',color:'Red shown · Blue also in the drop',image:'assets/fur-mama-red-studio-DRAFT.png',sizes:{Small:{qty:1,price:null},Medium:{qty:2,price:null},'2XL':{qty:1,price:null},'3XL':{qty:1,price:null}}},
  dogdad: {name:'Best Dog Dad',color:'Black shown · Blue and gray also in the drop',image:'assets/best-dog-dad-black-studio-DRAFT.png',sizes:{'2XL':{qty:null,price:null},'Other sizes':{qty:null,price:null}}},
  adopt: {name:'Adopt · Rescue · Foster',color:'Heather gray',image:'assets/adopt-rescue-foster-gray-studio-DRAFT.png',sizes:{Small:{qty:1,price:null},Medium:{qty:1,price:null},'2XL':{qty:1,price:null}}},
  sage: {name:'Cats Are My Favorite People',color:'Sage green',image:'assets/cats-favorite-people-sage.jpg',sizes:{Small:{qty:1,price:15},Medium:{qty:2,price:15},Large:{qty:2,price:15},XL:{qty:1,price:15},'2XL':{qty:0,price:17},'3XL':{qty:0,price:18}}},
  purple: {name:'Cats with Heart & Paws',color:'Heather purple',image:'assets/cats-heart-paws-purple.jpg',sizes:{Small:{qty:1,price:15},Medium:{qty:2,price:15},Large:{qty:1,price:15},XL:{qty:0,price:15},'2XL':{qty:2,price:17},'3XL':{qty:0,price:18}}},
  penholder: {name:'Paw Print Bookmark Pen Holder',color:'Black, gray, red & white paw print',image:'assets/bookmark-pen-holder-paw-print.png',sizes:{'One size':{qty:null,price:null}}}
};
const dialog=document.querySelector('#productDialog'),dialogImage=document.querySelector('#dialogImage'),dialogName=document.querySelector('#dialogName'),dialogColor=document.querySelector('#dialogColor'),dialogPrice=document.querySelector('#dialogPrice'),sizeGrid=document.querySelector('#sizeGrid'),sizeMessage=document.querySelector('#sizeMessage'),addButton=document.querySelector('#addToCart');
const drawer=document.querySelector('#cartDrawer'),scrim=document.querySelector('#scrim'),cartItems=document.querySelector('#cartItems'),cartTotal=document.querySelector('#cartTotal'),cartCount=document.querySelector('#cartCount'),checkoutButton=document.querySelector('#checkoutButton'),toast=document.querySelector('#toast');
let activeProduct=null,activeSize=null,cart=[];
function openProduct(id){activeProduct=id;activeSize=null;const p=products[id];dialogImage.src=p.image;dialogImage.alt=p.name;dialogName.textContent=p.name;dialogColor.textContent=p.color;const first=Object.values(p.sizes)[0];dialogPrice.textContent=first.price===null?'Price to confirm':`$${first.price}`;sizeGrid.innerHTML='';Object.entries(p.sizes).forEach(([size,data])=>{const b=document.createElement('button');b.type='button';b.className='size-option';b.disabled=data.qty===0;const detail=data.qty===null?'Inventory to confirm':data.qty?`${data.qty} left · $${data.price}`:'Sold out';b.innerHTML=`<strong>${size}</strong><small>${detail}</small>`;b.addEventListener('click',()=>selectSize(size,b));sizeGrid.appendChild(b)});sizeMessage.textContent=first.price===null?'Angelica’s Square price and quantity must be confirmed before this item can be purchased.':'Select an available size to continue.';addButton.textContent='Add to bag';addButton.disabled=true;dialog.showModal()}
function selectSize(size,button){activeSize=size;document.querySelectorAll('.size-option').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');const data=products[activeProduct].sizes[size];if(data.price===null){dialogPrice.textContent='Price to confirm';sizeMessage.textContent='Square item setup is needed before checkout can be enabled.';addButton.textContent='Available after Square setup';addButton.disabled=true;return}dialogPrice.textContent=`$${data.price}`;sizeMessage.textContent=`${data.qty} available in ${size}.`;addButton.textContent='Add to bag';addButton.disabled=false}
function addToCart(){if(!activeProduct||!activeSize)return;const p=products[activeProduct],d=p.sizes[activeSize];cart.push({id:crypto.randomUUID(),product:activeProduct,size:activeSize,price:d.price});dialog.close();renderCart();showToast(`${p.name} · ${activeSize} added to your bag`);openCart()}
function renderCart(){cartCount.textContent=cart.length;checkoutButton.disabled=!cart.length;if(!cart.length){cartItems.innerHTML='<p class="empty-cart">Your bag is waiting for something happy.</p>'}else{cartItems.innerHTML=cart.map(item=>{const p=products[item.product];return `<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${p.color} · ${item.size}</p><button data-remove="${item.id}" type="button">Remove</button></div><strong>$${item.price}</strong></div>`}).join('')}cartTotal.textContent=`$${cart.reduce((sum,item)=>sum+item.price,0).toFixed(2)}`;document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart=cart.filter(i=>i.id!==b.dataset.remove);renderCart()}))}
function openCart(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.classList.add('show')}function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.classList.remove('show')}function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.product)));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});addButton.addEventListener('click',addToCart);document.querySelector('#openCart').addEventListener('click',openCart);document.querySelector('#closeCart').addEventListener('click',closeCart);scrim.addEventListener('click',closeCart);checkoutButton.addEventListener('click',()=>showToast('Mockup only — production checkout will open Square securely.'));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.product-card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter})}));
const storyForm=document.querySelector('#storyForm'),storyFormStatus=document.querySelector('#storyFormStatus');storyForm.addEventListener('submit',async event=>{event.preventDefault();const submitButton=storyForm.querySelector('[type="submit"]');submitButton.disabled=true;submitButton.textContent='Sending…';storyFormStatus.className='form-status';storyFormStatus.textContent='Sending your story…';try{const response=await fetch(storyForm.action,{method:'POST',body:new FormData(storyForm),headers:{Accept:'application/json'}});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.error||'Submission failed')}storyForm.reset();storyFormStatus.classList.add('success');storyFormStatus.textContent='Thank you! Your Happy Tail Story was sent for review.'}catch(error){storyFormStatus.classList.add('error');storyFormStatus.textContent=`We could not send your story: ${error.message}. Please try again.`}finally{submitButton.disabled=false;submitButton.textContent='Submit your story'}});
